version: '2'

services:
  db:
    image: mysql:5.7.18
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/conf.d:/etc/mysql/conf.d
  dbadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "9282:80"
    links:
      - "db:db"
    depends_on:
      - db
  web:
    build: ./web
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./web/code:/code
    ports:
      - "8989:8000"
    links:
      - "db:db"
    depends_on:
      - db
