version: '2'

services:
  db:
    image: mysql:5.7.18
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/conf.d:/etc/mysql/conf.d
  dbadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "9282:80"
    links:
      - "db:db"
    depends_on:
      - db
